spring:
  port: 8080
  application:
    name: greeting-service

greeting-service:
  greeting: "Ciao"
  defaultValue: "Mondo"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS